CREATE USER :APP_USER WITH PASSWORD :'APP_PASSWORD';

--ACCESS DB
REVOKE CONNECT ON DATABASE :POSTGRES_DB FROM PUBLIC;
GRANT  CONNECT ON DATABASE :POSTGRES_DB TO   :APP_USER;

--ACCESS SCHEMA
REVOKE ALL     ON SCHEMA public FROM PUBLIC;
GRANT  USAGE   ON SCHEMA public TO   :APP_USER;

--ACCESS TABLES
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE
ON ALL TABLES IN SCHEMA public
TO :APP_USER;

--ACCESS SEQUENCES
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO :APP_USER;

--ACCESS FUTURE TABLES
ALTER DEFAULT PRIVILEGES
    FOR USER postgres
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE ON TABLES TO :APP_USER;

--ACCESS FUTURE SEQUENCES
ALTER DEFAULT PRIVILEGES
    FOR USER postgres
    IN SCHEMA public
    GRANT SELECT, USAGE ON SEQUENCES TO :APP_USER;
